# RBA Exchange Rates

In [1]:
import pandas as pd

In [30]:
rba_data_2009 = pd.read_excel("../raw-data/RBA_Exchange_Rates/exchange_rate_1969_2009.xls")
rba_data_2025 = pd.read_excel("../raw-data/RBA_Exchange_Rates/exchange_rate_2010-2025.xls")

In [15]:
rba_data_2009.columns = rba_data_2009.iloc[4,:].values

Units    Units
JPY        JPY
USD        USD
EUR        EUR
KRW        KRW
NZD        NZD
CNY        CNY
GBP        GBP
TWD        TWD
SGD        SGD
IDR        IDR
HKD        HKD
MYR        MYR
SDR        SDR
Index    Index
NaN        NaN
Name: 4, dtype: object

In [21]:
rba_data_2009 = rba_data_2009.iloc[10:,:-1]
rba_data_2009.rename(columns={"Units":"Date"},inplace=True)
rba_data_2009["Date"] = pd.to_datetime(rba_data_2009["Date"])
rba_data_2009

,Date,JPY,USD,EUR,KRW,NZD,CNY,GBP,TWD,SGD,IDR,HKD,MYR,SDR,Index
10,1969-07-31,400.74,1.1138,NaN,NaN,0.998,NaN,0.4657,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,1969-08-31,398.14,1.1091,NaN,NaN,0.998,NaN,0.4657,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,1969-09-30,396.81,1.1094,NaN,NaN,0.998,NaN,0.4657,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,1969-10-31,399.02,1.1158,NaN,NaN,0.998,NaN,0.4657,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,1969-11-30,399.08,1.1161,NaN,NaN,0.998,NaN,0.4657,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
491,2009-08-31,77.88,0.8393,0.5877,1048.12,1.2296,5.7336,0.5168,27.61,1.2109,8460,6.5054,2.9556,0.5366,66.3
492,2009-09-30,78.82,0.8801,0.6015,1037.9,1.2193,6.0083,0.5487,28.3,1.2445,8511,6.8209,3.0579,0.5579,68.2
493,2009-10-31,83.49,0.9161,0.6169,1083.7,1.251,6.2547,0.5533,29.76,1.2794,8740,7.1,3.1244,0.5771,70.7
494,2009-11-30,79.24,0.9178,0.6092,1064.92,1.2738,6.2669,0.5539,29.54,1.269,8678,7.1131,3.1072,0.57,69.9
495,2009-12-31,82.82,0.8969,0.6241,1045.86,1.2354,6.1228,0.5581,28.84,1.2589,8429,6.9553,3.0714,0.5742,69.7

In [31]:
rba_data_2025
rba_data_2025.columns = rba_data_2025.iloc[4,:].values
rba_data_2025 = rba_data_2025.iloc[10:,:]
rba_data_2025.rename(columns={"Units":"Date"},inplace=True)
rba_data_2025["Date"] = pd.to_datetime(rba_data_2025["Date"])
rba_data_2025

,Date,USD,Index,CNY,JPY,EUR,KRW,GBP,SGD,INR,...,AED,PGK,HKD,CAD,ZAR,SAR,CHF,SEK,PHP,SDR
10,2010-01-29,0.8909,69.2,6.083,80.12,0.6395,1030.59,0.5523,1.253,41.32,...,3.2718,2.4111,6.92,0.9517,6.7897,3.3411,0.9387,6.5618,NaN,0.5723
11,2010-02-26,0.8899,69.5,6.075,79.42,0.6551,1031.75,0.5826,1.2532,41.18,...,3.2682,2.4414,6.9078,0.9417,6.8909,3.3374,0.9585,6.3705,NaN,0.5819
12,2010-03-31,0.9159,71.7,6.252,85.55,0.6827,1037.49,0.6072,1.284,41.34,...,3.3636,2.5231,7.1108,0.9325,6.7639,3.4346,0.9767,6.6548,NaN,0.6028
13,2010-04-30,0.93,72.5,6.3486,87.49,0.7023,1030.77,0.6065,1.2719,41.34,...,3.4154,2.562,7.2217,0.9335,6.8474,3.4878,1.0077,6.7523,NaN,0.6166
14,2010-05-31,0.849,67.5,5.7971,77.71,0.6901,1016.93,0.5876,1.1898,39.39,...,3.118,2.4051,6.6149,0.8901,6.4566,3.1841,0.9818,6.6427,NaN,0.5759
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,2025-03-31,0.628,59.6,4.5548,93.62,0.5796,923.63,0.4847,0.8421,53.67,...,2.3063,NaN,4.885,0.899,NaN,NaN,0.5521,NaN,35.98,0.4738
193,2025-04-30,0.6416,59.9,4.6613,91.43,0.5637,911.63,0.4788,0.8375,54.58,...,2.3563,NaN,4.9768,0.8871,NaN,NaN,0.5283,NaN,35.83,0.4728
194,2025-05-30,0.6436,59.6,4.6259,92.57,0.567,887.78,0.4775,0.8295,54.95,...,2.3636,NaN,5.0463,0.889,NaN,NaN,0.5296,NaN,35.8,0.4751
195,2025-06-30,0.655,60.1,4.6921,94.26,0.5586,883.89,0.4771,0.8341,55.99,...,2.4055,NaN,5.1416,0.8947,NaN,NaN,0.5228,NaN,36.88,0.4769
196,2025-07-31,0.6469,60.3,4.6532,96.25,0.5656,899.32,0.4877,0.8376,56.66,...,2.3757,NaN,5.078,0.894,NaN,NaN,0.5257,NaN,37.78,0.4752

In [37]:
rba_data_2009.shape

(486, 15)

In [34]:
df_merged = pd.concat([rba_data_2009, rba_data_2025], ignore_index=True, sort=False)
df_merged.shape

(673, 26)

In [39]:
df_merged.to_csv("../processed-csvs/rba_interest_rates.csv")